---
  name: Build
  
  on: workflow_dispatch
  
  jobs:
    build:
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest]
      runs-on: ${{matrix.os}}
      timeout-minutes: 1
      steps:
  
        - name: Checkout Repository
          uses: actions/checkout@v4
  
        - name: Create build directory
          shell: bash
          run: mkdir build
  
        - name: CMake Setup
          working-directory: build
          shell: bash
          run: |
            cmake .. -G make
  
        - name: Build
          working-directory: build
          run: cmake --build . --config Release --target all
          shell: bash

        - name: Upload Executable
          uses: actions/upload-artifact@v4
          with:
            name: Executable-${{matrix.os}}
            path: build/exe_file

        - name: Test
          working-directory: build
          continue-on-error: true
          run: |
            if [ "${{matrix.os}}" == "windows-latest" ]; then
              ctest --verbose > TestResults.log
            else
              ctest --verbose | tee TestResults.log
            fi
          shell: bash

        - name: Upload Test Results
          if: matrix.os != 'windows-latest'
          uses: actions/upload-artifact@v4
          with:
            name: Test.${{matrix.os}}.log
            path: build/TestResults.log