---
  name: Build
  
  on: workflow_dispatch
  
  jobs:
    build:
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest]
      runs-on: ${{matrix.os}}
      timeout-minutes: 1
      steps:
  
        - name: Checkout Repository
          uses: actions/checkout@v4
  
        - name: Create build directory
          shell: bash
          run: mkdir build
  
        - name: Ubuntu Setup packages
          if: matrix.os != 'macos-latest'
          shell: bash
          run : |
            sudo apt-get install ninja-build

        - name: MacOS Setup packages
          if: matrix.os == 'macos-latest'
          shell: bash
          run : |
            brew install ninja
  
        - name: CMake Setup
          working-directory: build
          shell: bash
          run: |
            cmake .. -G Ninja
  
        - name: Build
          working-directory: build
          shell: bash
          run: |
            cmake --build . --config Release --target all
        - uses: actions/upload-artifact@v4
          with:
            name: Executable-${{matrix.os}}
            path: |
              build/exe_file

        - name: Test
          working-directory: build
          shell: bash
          continue-on-error: true
          run: |
            ctest --verbose | tee TestResults.log
        - uses: actions/upload-artifact@v4
          with:
            name: Test.${{matrix.os}}.log
            path: |
              build/Testing/Temporary/LastTest.log
              build/TestResults.log